Design UI and authencation user for login screen
duyanh24/Mp3App pull request #8
Opened 2020-10-12 09:50 UTC by duyanh24

2020-10-12 10:08 UTC, mlh-hieutq requested changes

2020-10-12 10:08 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +        return email.count > 6 && password.count > 6
Anh nghĩ đoạn này mình nên tách thành 2 func. Một func thực hiện validate email, một func thực hiện validate password.

2020-10-12 10:08 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        AccountDefault.shared.saveStringData(data: password, key: .passwordKey)
Password này em lưu có sử dụng mã hóa gì không em? Hay là mình lưu dạng plain text em.

2020-10-12 10:32 UTC, duyanh24 commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        AccountDefault.shared.saveStringData(data: password, key: .passwordKey)
có e định mã hoá nhưng để xử lý sau

2020-10-13 03:32 UTC, mlh-hieutq requested changes

2020-10-13 03:32 UTC, mlh-hieutq commented on Mp3App/Utils/CustomView/ProgressHUB.swift
> +//  ProgressHUB.swift
Tên file phải là `ProgressHUD.swift` chứ nhỉ?

2020-10-13 03:34 UTC, mlh-hieutq requested changes

2020-10-13 03:34 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +            } else {
Em kiểm tra lại logic đoạn này nhé. Theo anh nghĩ là trước khi gọi API thì mình cần validate cả email và password trước.

2020-10-13 03:39 UTC, mlh-hieutq requested changes

2020-10-13 03:39 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        self.loginResult.onNext(.failure(APIError(status_code: nil, status_message: ErrorMessage.unknownError)))
Chỗ này em xem xét xem có thể đưa đoạn này vào trong hàm khởi tạo của APIError không nhé. Input là Firebase Error, còn Output là APIError.

2020-10-13 03:43 UTC, duyanh24 commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        self.loginResult.onNext(.failure(APIError(status_code: nil, status_message: ErrorMessage.unknownError)))
e thấy mấy lỗi này cũng tương tự nhau nên đưa vào APIError luôn, e nghĩ firebase thì nó cũng là gọi api :D

2020-10-13 03:45 UTC, mlh-hieutq commented on Mp3App/Features/Login/LoginViewModel.swift
> +        var loginSuccess: Observable<Result<Void, Error>>
Tên biến này anh thấy cũng không hợp lý lắm vì nó đang trả về cả error. Anh nghĩ nên đổi thành `loginResult`.

2020-10-13 03:47 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        self.loginResult.onNext(.failure(APIError(status_code: nil, status_message: ErrorMessage.unknownError)))
Ý anh là muốn em đưa đoạn convert từ  Firebase Error này của em gom vào một chỗ với APIError ấy. Vì em còn gọi nhiều service khác trên firebase. Thì đoạn này có thể bị lặp code ấy.

2020-10-13 03:50 UTC, mlh-hieutq requested changes

2020-10-13 03:50 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        self.loginResult.onNext(.failure(APIError(status_code: nil, status_message: ErrorMessage.unknownError)))
Ví dụ trong APIError có hàm init(authErrorCode: AuthErrorCode?) như này chẳng hạn.

2020-10-13 03:50 UTC, mlh-hieutq commented on Mp3App/Networking/Database/FirebaseDatabase/FirebaseAccount.swift
> +                        self.loginResult.onNext(.failure(APIError(status_code: nil, status_message: ErrorMessage.unknownError)))
Rồi từ authErrorCode truyền vào mình sẽ set status_code và status_message cho phù hợp ấy.

2020-10-13 07:50 UTC, mlh-hieutq approved these changes

2020-10-13 07:53 UTC, merged